# conda env create -f environment.yml
name: ulmRBM
channels:
  - conda-forge
  - defaults
dependencies:
  # actually needed
  - python=3.12
  - numpy
  - scipy
  - fenics-dolfinx=0.10
  - mpich
  - pip
  - pip:
      - -e .
  # for space-time kronecker products (optional)
  - pip:
      - git+https://github.com/mfeuerle/kron
  # for testing
  - pytest
  - pytest-cov
  # for performance
  - mkl
  - blas=*=*mkl
  # for documentation
  - sphinx
  - pydata-sphinx-theme
  # for plotting
  - matplotlib
  - pyvista
